### ISSUE TITLE
Want a switch of whether add `- Copied By ClipSync` to text

### ISSUE THREAD

**Issue by QZLin** [pishangujeniya/clipsync-windows#6]
I need to transfer the original text between devices, and always have to manually delete the `- Copied By ClipSync` .
Could you add a switch to close this?

**Comment by QZLin** [comment]
Hmm... I read the source and knew that the "watermark" is used to avoid the problem of re-copying the transmitted text. Maybe there are other ways to solve this problem?

**Comment by pishangujeniya** [comment]
@QZLin  Your guessing is correct, its only used to avoid infinite looping of recopying the text.
