### ISSUE TITLE
Server address was not used when starting the server

### ISSUE THREAD

**Issue by QZLin** [pishangujeniya/clipsync-windows#7]
In `StartServerButton_Click` method, variable `url` does not use the value of the textbox.

https://github.com/pishangujeniya/clipsync-windows/blob/caf664b8a0f74ef766e5a9df19de8267c52f78cd/ClipSyncWindowsFormApplication/ClipSyncController.cs#L179
It should be:
```csharp
string url = "http://" + this.serverAddressTextBox.Text + ":" + this.serverPortTextBox.Text + "/";
```

**Comment by pishangujeniya** [comment]
It is not used intentionally,
If the server address is made specific then only that IP Address are allowed to connect, so to avoid that, we used `*`
